apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: anime-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: anime-b
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 65